import socket
import os
import subprocess
import re

def get_local_ip():
    """Returns the most likely local LAN IP address."""
    try:
        s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        s.connect(('8.8.8.8', 80))
        IP = s.getsockname()[0]
        s.close()
        if not IP.startswith('127.'):
            return IP
    except:
        pass

    try:
        output = subprocess.check_output("ipconfig", shell=True).decode()
        ips = re.findall(r"IPv4 Address[\. ]+: (192\.168\.\d+\.\d+|10\.\d+\.\d+\.\d+|172\.(1[6-9]|2[0-9]|3[0-1])\.\d+\.\d+)", output)
        if ips:
            return ips[0][0]
    except:
        pass
        
    return '127.0.0.1'

def sync_mobile_env():
    local_ip = get_local_ip()
    mobile_env_path = os.path.join("mobile-app", ".env.local")
    
    print(f"Detected Local IP: {local_ip}")
    
    content = [
        "# Auto-generated by EnerQoT Sync",
        f"EXPO_PUBLIC_API_BASE_URL=http://{local_ip}:5000",
        "EXPO_PUBLIC_ENV_NAME=local"
    ]
    
    with open(mobile_env_path, "w") as f:
        f.write("\n".join(content))
    
    print(f"Updated {mobile_env_path} successfully!")

if __name__ == "__main__":
    sync_mobile_env()
